### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by maxlerebourg**

### CODE REVIEW

**Comment by maxlerebourg** [comment]
Can't test the PR, be careful

**Comment by maxlerebourg** [comment]
I just wanted to use one volume for all my DAVs folder and with ENTRYPOINT create all the folder I need.
```
entrypoint: mkdir -p /root/dav1 /root/dav2
volumes:
  - data:/root/
```
portion of docker-compose.yml
The CMD launch the server like before.
Maybe I'm totally wrong...

**Comment by 117503445** [comment]
I think a more elegant solution to your needs should exist. But I'm very busy these days, so I'll try to solve this problem in a few days.

**Comment by maxlerebourg** [comment]
Yes, I can use this solution. I will submit PR to create folder at the
start of the program when I will have time.
Thanks a lot.

**Comment by 117503445** [comment]
Sorry, exposing the host file system as a WebDAV is one of the core usage scenarios of this project. In this scenario, there is no need to create folders in the form of Entrypoint. You can modify your docker-compose file, or fork this project and do what you want.

**Pull request closed without merging**
