### PR TITLE
Supports root `/` dav

### PR DESCRIPTION
**Pull request by Jipok**
Examples:
`/pub,./pub,null,null,true;/,./data,null,null,false;`
`/pub,./data/pub,null,null,true;/,./data,null,null,false;`

### CODE REVIEW

**Comment by 117503445** [comment]
Currently each dav is non-conflicting, e.g. `/data1` and `/data2`, each dav corresponds to a local folder. But `/` and `/pub` do conflict.

Conflicting dav names can be confusing for users, so what is the benefit of allowing dav name conflicts?

**Comment by Jipok** [comment]
> But / and /pub do conflict.

I made confilct check. So user will be notified if wrong order in `--dav`.
And after run only one limit here - you just cant make `pub` dir in `/` dave

> what is the benefit of allowing dav name conflicts?

Well, if you only need one dav, then you want to see a beautiful address without an extra element after `/`. And after logging in, you can immediately see a list of files, and not an almost empty white page with one link.

Feel free to reject this pr. I'll just create a fork. Anyway, I wanted to add user support through the `Remote-User` header (for [Jauth](https://github.com/Jipok/Jauth)).

**Comment by 117503445** [comment]
So actually, this feature is designed to support single dav?

Wouldn't it be possible to tell the user "Error: '/' is overwritten and cannot be accessed" when they have entered multiple davs and one dav is /?

**Review by 117503445 — APPROVED** [review]
lgtm

**Pull request merged**
