### PR TITLE
Some features

### PR DESCRIPTION
**Pull request by Jipok**
I want to slightly modify the frontend to suit my needs. For example, remove unnecessary buttons and add ,y own. With this flag, I don’t have to rebuild the project and upload it to the server every time there is a change.

With this PR, I think I achieved everything I wanted from GoWebDAV. And most likely I won’t bother you anymore.

### CODE REVIEW

**Comment by Jipok** [comment]
Another feature that I was missing was the ability to share a server without a login and password. Just a link. By adding index hiding I achieved security when hosting the server publicly. Without knowing the link, you will not be able to get any response from the server.

While implementing this feature, I noticed that after refactoring you added `enableSingleDavMode`. I tried for a long time to understand why it was needed, but I couldn’t. I removed the code associated with this and the server behavior did not change at all. I tested with:
1) The only ones dav `/`
2) The only dav `/somename`
3) Two different davs
4) Two davs, one `/`. Here, as expected, the server threw an error
`indexHandler` works correctly in all cases.

**Comment by Jipok** [comment]
In fact, I needed a different ui just to not display the buttons for read-only mode. I'll redo it tomorrow.

**Comment by Jipok** [comment]
The latest commit allows this:
`--dav "/secret1,../dir1; /secret2,./dir2;" `

**Comment by Jipok** [comment]
@117503445
I'm done with this

**Review by 117503445 — APPROVED** [review]
LGTM

**Comment by 117503445** [comment]
> A separate code for the read-only version is no longer needed. I made changes to the front itself and it now independently determines write access. [dom111/webdav-js#132](https://github.com/dom111/webdav-js/pull/132)
> 
> Since the project has been inactive for several years, I would not hope for a quick acceptance of the PR. Perhaps he will not be accepted at all. Therefore, I recommend specifying a link to the fork in the build script: https://github.com/Jipok/webdav-js

done

**Pull request merged**
